### ISSUE TITLE
yarn run build fails 

### ISSUE THREAD

**Issue by nisarhassan12** [GTBitsOfGood/website#87]
Hi! I'm was trying to build the site but if failed with the following error:

![image](https://user-images.githubusercontent.com/46004116/80279063-8e9d7180-8714-11ea-949d-c2c48fcb6136.png)

How can I provide the access token. Thanks

**Comment by ghost** [comment]
Sorry for the late reply, but this is because you'll need our Contentful access token for the text content to display! This gets defined in a `.env` file that the build script looks for when it goes to fetch the content. Right now, we're unable to give this key to outside contributors for security reasons. We'll find a way to make our repo more accessible to newcomers in the future 😁 

Closing this for now. We'll add a note to our `CONTRIBUTING.md` about this.

**Comment by nisarhassan12** [comment]
Thanks! @Holben888
